coverage:
  precision: 2
  range:
    - 65.0
    - 100.0
  round: down
  status:
    project:
      default:
        target: 70%
        threshold: 10%
    patch:
      default:
        target: 50%
        threshold: 10%
