name: 'Module fouriernl'

on:
  push:
    branches: [ main ]
    paths:
      - modules/fouriernl/**
  pull_request:
    branches: [ main ]
    paths:
      - modules/fouriernl/**
  workflow_dispatch:

env:
  MODULE_DIR: 'modules/fouriernl'

  MODULE: 'fouriernl'

  # CTest
  CT_OPTS: "--timeout 300 --output-on-failure"

  # MPI
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  OMPI_MCA_rmaps_base_oversubscribe: 1

jobs:
  check-runner:
    name: 'Check runner'
    uses: 'arcaneframework/gh_actions/.github/workflows/check_runner.yml@v3'
    secrets: inherit
    with:
      requested_runner_tag: 'gpu'
      is_requested_runner_a_gpu_runner: true

  tests:
    name: 'Build and Test'
    needs: check-runner
    runs-on: ${{ needs.check-runner.outputs.runner_tag }}
    container:
      image: ghcr.io/arcaneframework/arcane_ubuntu-2404:gcc-14_full_check_latest
      options: ${{ case(needs.check-runner.outputs.is_a_gpu_runner == 'true', '--runtime nvidia --gpus all', '') }}

    steps:
      - name: Define environment paths
        shell: bash
        run: |
          echo "SOURCE_DIR=${GITHUB_WORKSPACE}/src" >> $GITHUB_ENV
          echo "BUILD_DIR=${GITHUB_WORKSPACE}/build" >> $GITHUB_ENV
          echo "CT_RESULT_DIR=${GITHUB_WORKSPACE}/test" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          path: ${{ env.SOURCE_DIR }}

      - name: Configure
        shell: bash
        run: |
          cmake \
          -S ${{ env.SOURCE_DIR }} \
          -B ${{ env.BUILD_DIR }} \
          -GNinja

      - name: Build
        shell: bash
        run: |
          cmake --build ${{ env.BUILD_DIR }}

      - name: Test
        shell: bash
        run: |
          mkdir -p ${{ env.CT_RESULT_DIR }}
          ctest --test-dir ${{ env.BUILD_DIR }} --output-junit ${{ env.CT_RESULT_DIR }}/results.xml ${{ env.CT_OPTS }} -R '\[${{ env.MODULE }}\]'

      - name: Upload test artifact
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: tests-${{ env.MODULE_DIR }}-artifact
          path: ${{ env.CT_RESULT_DIR }}
          retention-days: 7
